spring:
  application:
    name: cash
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/finclave
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:9090/realms/finclave
        registration:
          finclave:
            provider: keycloak
            authorizationGrantType: client_credentials
            client-id: finclave
            client-secret: Fdx84febgALBIuFdC1jLzSl6mT8PxJwa
            scope: profile
            clientAuthenticationMethod: client_secret_post

server:
  port: 8084

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
