spring:
  application:
    name: front

feign:
  account: http://localhost:8091/account
  exchange: http://localhost:8091/exchange
  cash: http://localhost:8091/cash
  transfer: http://localhost:8091/transfer
  notification: http://localhost:8091/notification

server:
  port: 8080
