spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: account
              uri: lb://account
              predicates:
                - Path=/account/**
            - id: blocker
              uri: lb://blocker
              predicates:
                - Path=/blocker/**
            - id: cash
              uri: lb://cash
              predicates:
                - Path=/cash/**
            - id: exchange
              uri: lb://exchange
              predicates:
                - Path=/exchange/**
            - id: exchange-generator
              uri: lb://exchange-generator
              predicates:
                - Path=/exchange-generator/**
            - id: notification
              uri: lb://notification
              predicates:
                - Path=/notification/**
            - id: transfer
              uri: lb://transfer
              predicates:
                - Path=/transfer/**
          default-filters:
            - StripPrefix=1
    loadbalancer:
      configurations: health-check

server:
  port: 8091

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8092/eureka/
