spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: account
              uri: lb://account
              predicates:
                - Path=/account/**
            - id: blocker
              uri: lb://blocker
              predicates:
                - Path=/blocker/**
            - id: cash
              uri: lb://cash
              predicates:
                - Path=/cash/**
            - id: exchange
              uri: lb://exchange
              predicates:
                - Path=/exchange/**
            - id: exchange-rate
              uri: lb://exchange-rate
              predicates:
                - Path=/exchange-rate/**
            - id: notification
              uri: lb://notification
              predicates:
                - Path=/notification/**
            - id: transfer
              uri: lb://transfer
              predicates:
                - Path=/transfer/**
          default-filters:
            - StripPrefix=1
    loadbalancer:
      configurations: health-check

circuit-breaker:
  timeout: 5

server:
  port: 8091

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
